name:                deadlinks
version:             0.1.0.0
github:              "githubuser/deadlinks"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/deadlinks#readme>

dependencies:
- base >= 4.7 && < 5
- req <= 3.8.0
- bytestring
- modern-uri <= 0.3.3.1
- text
- aeson <= 1.5.5.1
- cmark <= 0.6

library:
  source-dirs: src

executables:
  deadlinks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadlinks

tests:
  deadlinks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadlinks
